"""Label-quality and composition audit for every split of a YOLO dataset.

    python3 audit_labels.py --data master_traffic_violation_dataset/data.yaml
    python3 audit_labels.py --data eval/clean_splits/data.yaml --check-images

Writes ``eval/results/label_audit.{json,md}``: malformed labels, duplicate
boxes, WithHelmet/WithoutHelmet contradictions in the annotations, tiny-object
share per class, and which upstream source each split's instances come from.
See ``modules/label_audit.py`` for what each check means and why it matters.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

from modules import yolo_io
from modules.label_audit import (
    TINY_AREA,
    audit_split,
    disjoint_label_groups,
    dominant_source_share,
    source_of,
)
from modules.logging_setup import configure_logging, get_logger

log = get_logger("audit_labels")
SPLITS = ("train", "val", "test")


def render_markdown(p: dict) -> str:
    names = p["class_names"]
    lines = [
        "# Label-quality and composition audit",
        "",
        f"- Data: `{p['data']}` (dataset version `{p['dataset_version']}`)",
        f"- Tiny box = area < {TINY_AREA:.5f} of the image (a 16 px square at 640).",
        "- Generated by `audit_labels.py`; every number is counted from the files.",
        "",
        "## Integrity",
        "",
        "| split | images | background | malformed lines | duplicate boxes | "
        "helmet contradictions | unreadable images |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for split, r in p["splits"].items():
        lines.append(
            f"| {split} | {r['images']} | {r['background_images']} | "
            f"{sum(r['malformed_labels'].values())} | {r['duplicate_boxes']} | "
            f"{r['helmet_contradictions']} | "
            f"{'—' if r['unreadable_images'] is None else r['unreadable_images']} |")
    lines += ["", "## Object size — share of tiny boxes / median box area", "",
              "| split | " + " | ".join(names) + " |", "|---|" + "---:|" * len(names)]
    for split, r in p["splits"].items():
        cells = []
        for n in names:
            c = r["per_class"][n]
            cells.append("—" if not c["instances"] else
                         f"{c['tiny_share']:.1%} / {c['median_area_pct']}%")
        lines.append(f"| {split} | " + " | ".join(cells) + " |")
    lines += ["", "## Where each split's instances come from", "",
              "Source = upstream export, from the filename prefix. `aug` = the offline-"
              "augmented training images (their origin is not recoverable from the name).",
              ""]
    for split, r in p["splits"].items():
        lines += [f"**{split}**", "", "| source | images | " + " | ".join(names) + " |",
                  "|---|---:|" + "---:|" * len(names)]
        for src, k in r["sources"].items():
            cls = r["source_class_instances"].get(src, {})
            lines.append(f"| `{src}` | {k} | " +
                         " | ".join(str(cls.get(n, 0)) for n in names) + " |")
        lines.append("")
        dom = []
        for n in names:
            src, share = dominant_source_share(r, n)
            if src:
                dom.append(f"{n}: {share:.0%} from `{src}`")
        lines += ["Dominant source per class — " + "; ".join(dom) + ".", ""]
    lines += ["## Label coverage", ""]
    for split, r in p["splits"].items():
        groups = r.get("disjoint_label_groups") or []
        verdict = ("**classes split into groups that never share a labelled image**: "
                   + " | ".join(", ".join(g) for g in groups)) if len(groups) > 1 \
            else "every class co-occurs with another in at least one image"
        lines.append(f"- **{split}**: {verdict}")
    probe = p.get("model_probe")
    if probe:
        lines += ["", f"### What the model predicts per source — `{probe['model']}` on "
                  f"`{probe['split']}` (conf ≥ {probe['conf']})", "",
                  "Share of each source's images with at least one prediction of the "
                  "class. A class the model almost never predicts on a source whose "
                  "labels omit it was learned as background there.", "",
                  "| source | images | " + " | ".join(names) + " |",
                  "|---|---:|" + "---:|" * len(names)]
        for src, row in probe["by_source"].items():
            lines.append(f"| `{src}` | {row['images']} | " + " | ".join(
                f"{row['share_with_prediction'][n]:.0%}" for n in names) + " |")
    lines.append("")
    return "\n".join(lines) + "\n"


def probe_model(model_path: str, data: dict, split: str, conf: float = 0.25) -> dict:
    """Per source: share of images where the model predicts each class."""
    from collections import defaultdict

    from ultralytics import YOLO

    model = YOLO(model_path)
    names = data["names"]
    per: dict = defaultdict(lambda: {"images": 0, "with": {n: 0 for n in names}})
    for image_path, _ in yolo_io.iter_image_label_pairs(yolo_io.split_dir(data, split)):
        src = source_of(image_path)
        r = model.predict(source=image_path, conf=conf, verbose=False)[0]
        per[src]["images"] += 1
        for n in {names[int(b.cls[0])] for b in r.boxes}:
            per[src]["with"][n] += 1
    return {"model": model_path, "split": split, "conf": conf, "by_source": {
        s: {"images": v["images"],
            "share_with_prediction": {n: round(v["with"][n] / v["images"], 4) for n in names}}
        for s, v in sorted(per.items())}}


def parse_args(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--data", default="master_traffic_violation_dataset/data.yaml")
    ap.add_argument("--check-images", action="store_true",
                    help="also decode every image (slow on the 12 GB train split)")
    ap.add_argument("--model", default=None,
                    help="optional weights: probe what the model predicts per source")
    ap.add_argument("--probe-split", default="val")
    ap.add_argument("--out", default="eval/results")
    ap.add_argument("--name", default="label_audit")
    return ap.parse_args(argv)


def main(argv=None) -> int:
    configure_logging()
    args = parse_args(argv)
    if not os.path.exists(args.data):
        log.error("data.yaml not found: %s", args.data)
        return 2
    from modules.provenance import dataset_fingerprint

    data = yolo_io.load_data_yaml(args.data)
    names = data["names"]
    splits = {}
    for split in SPLITS:
        d = yolo_io.split_dir(data, split)
        if not d or not os.path.isdir(d):
            continue
        log.info("auditing %s", split)
        splits[split] = audit_split(yolo_io.iter_image_label_pairs(d), names,
                                    check_images=args.check_images)
        splits[split]["disjoint_label_groups"] = disjoint_label_groups(splits[split])
    payload = {"data": args.data, "class_names": names,
               "dataset_version": dataset_fingerprint(args.data)["version"],
               "splits": splits}
    if args.model:
        payload["model_probe"] = probe_model(args.model, data, args.probe_split)
    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, args.name + ".json"), "w") as fh:
        json.dump(payload, fh, indent=2, sort_keys=True)
    with open(os.path.join(args.out, args.name + ".md"), "w") as fh:
        fh.write(render_markdown(payload))
    print(f"wrote {os.path.join(args.out, args.name)}.md/.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
